version: "3.0"
services:
  go-server:
    build: "./app"
    env_file:
      - "app/.env"
    ports:
      - "9000:8888"
    depends_on:
      - "mongo-server"
  mongo-server:
    restart: always
    image: mongo:4.2.0
    ports:
      - "27000:27017"
    volumes:
      - ./mongo/data:/data/db
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Tokyo
    networks:
      - default